[2025-05-04T19:22:54.734+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-04T19:22:54.747+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-04T19:22:52.175053+00:00 [queued]>
[2025-05-04T19:22:54.752+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-04T19:22:52.175053+00:00 [queued]>
[2025-05-04T19:22:54.752+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-04T19:22:54.760+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data_into_trino> on 2025-05-04 19:22:52.175053+00:00
[2025-05-04T19:22:54.765+0000] {standard_task_runner.py:63} INFO - Started process 1256 to run task
[2025-05-04T19:22:54.767+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_iceberg_example', 'insert_data_into_trino', 'manual__2025-05-04T19:22:52.175053+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dbt_iceberg_dag.py', '--cfg-path', '/tmp/tmp272qf4uv']
[2025-05-04T19:22:54.767+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask insert_data_into_trino
[2025-05-04T19:22:54.795+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_iceberg_example.insert_data_into_trino manual__2025-05-04T19:22:52.175053+00:00 [running]> on host 27fc0593f179
[2025-05-04T19:22:54.844+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_iceberg_example' AIRFLOW_CTX_TASK_ID='insert_data_into_trino' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T19:22:52.175053+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T19:22:52.175053+00:00'
[2025-05-04T19:22:54.845+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-04T19:22:55.185+0000] {logging_mixin.py:188} INFO - Erro ao inserir dados: name 'sample_data' is not defined
[2025-05-04T19:22:55.188+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-04T19:22:55.188+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dbt_iceberg_dag.py", line 163, in insert_data_into_trino
    for product in sample_data:
NameError: name 'sample_data' is not defined
[2025-05-04T19:22:55.196+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_iceberg_example, task_id=insert_data_into_trino, run_id=manual__2025-05-04T19:22:52.175053+00:00, execution_date=20250504T192252, start_date=20250504T192254, end_date=20250504T192255
[2025-05-04T19:22:55.204+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task insert_data_into_trino (name 'sample_data' is not defined; 1256)
[2025-05-04T19:22:55.220+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-04T19:22:55.221+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
