[2025-05-05T09:29:46.112+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-05T09:29:46.131+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_iceberg_example.initialize_minio scheduled__2025-05-04T00:00:00+00:00 [queued]>
[2025-05-05T09:29:46.138+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_iceberg_example.initialize_minio scheduled__2025-05-04T00:00:00+00:00 [queued]>
[2025-05-05T09:29:46.138+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-05-05T09:29:46.147+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): initialize_minio> on 2025-05-04 00:00:00+00:00
[2025-05-05T09:29:46.151+0000] {standard_task_runner.py:63} INFO - Started process 73 to run task
[2025-05-05T09:29:46.153+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_iceberg_example', 'initialize_minio', 'scheduled__2025-05-04T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/dbt_iceberg_dag.py', '--cfg-path', '/tmp/tmpvqkyewam']
[2025-05-05T09:29:46.154+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask initialize_minio
[2025-05-05T09:29:46.192+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_iceberg_example.initialize_minio scheduled__2025-05-04T00:00:00+00:00 [running]> on host 27fc0593f179
[2025-05-05T09:29:46.246+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_iceberg_example' AIRFLOW_CTX_TASK_ID='initialize_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-04T00:00:00+00:00'
[2025-05-05T09:29:46.247+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-05T09:29:46.724+0000] {logging_mixin.py:188} INFO - Bucket 'iceberg-data' j√° existe
[2025-05-05T09:29:46.733+0000] {logging_mixin.py:188} INFO - Dados de produtos de exemplo carregados
[2025-05-05T09:29:46.740+0000] {logging_mixin.py:188} INFO - Dados de vendas de exemplo carregados
[2025-05-05T09:29:46.741+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-05T09:29:46.741+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-05T09:29:46.748+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_iceberg_example, task_id=initialize_minio, run_id=scheduled__2025-05-04T00:00:00+00:00, execution_date=20250504T000000, start_date=20250505T092946, end_date=20250505T092946
[2025-05-05T09:29:46.767+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-05T09:29:46.767+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-05-05T09:50:25.007+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-05T09:50:25.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_iceberg_example.initialize_minio scheduled__2025-05-04T00:00:00+00:00 [queued]>
[2025-05-05T09:50:25.026+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_iceberg_example.initialize_minio scheduled__2025-05-04T00:00:00+00:00 [queued]>
[2025-05-05T09:50:25.027+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-05-05T09:50:25.035+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): initialize_minio> on 2025-05-04 00:00:00+00:00
[2025-05-05T09:50:25.040+0000] {standard_task_runner.py:63} INFO - Started process 97 to run task
[2025-05-05T09:50:25.043+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_iceberg_example', 'initialize_minio', 'scheduled__2025-05-04T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_iceberg_dag.py', '--cfg-path', '/tmp/tmputyqy9yr']
[2025-05-05T09:50:25.044+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask initialize_minio
[2025-05-05T09:50:25.078+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_iceberg_example.initialize_minio scheduled__2025-05-04T00:00:00+00:00 [running]> on host 92b88004addd
[2025-05-05T09:50:25.133+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_iceberg_example' AIRFLOW_CTX_TASK_ID='initialize_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-04T00:00:00+00:00'
[2025-05-05T09:50:25.134+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-05T09:50:25.476+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-05T09:50:25.477+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/dbt_iceberg_dag.py", line 65, in initialize_minio
    s3_client.head_bucket(Bucket='iceberg-data')
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadBucket operation: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dbt_iceberg_dag.py", line 68, in initialize_minio
    s3_client.create_bucket(Bucket='iceberg-data')
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
[2025-05-05T09:50:25.486+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_iceberg_example, task_id=initialize_minio, run_id=scheduled__2025-05-04T00:00:00+00:00, execution_date=20250504T000000, start_date=20250505T095025, end_date=20250505T095025
[2025-05-05T09:50:25.493+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task initialize_minio (An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.; 97)
[2025-05-05T09:50:25.536+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-05T09:50:25.536+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
